#spring:
#  cloud:
#    azure:
#      active-directory:
#          profile:
#            tenant-id: 6bb41fe4-40a3-4a10-b6cd-38278e78b21a
#          credential:
#            client-id: 5edda4ee-b47b-42c4-af0d-88e57ae594aa
#            client-secret: 2014d854-d6ac-4cb5-bfab-c41a58572c3d
#
#
#server:
#  port: 8083
#  forward-headers-strategy: native